### ISSUE TITLE
Synchronous service call

### ISSUE THREAD

**Issue by galou** [ctu-mrs/ros2_uav_example#3]
In ` ros2_examples/src/service_client_example.cpp` you wrote that
```
status = result.wait_for(std::chrono::seconds(1));
```
"BLOCKS THE WHOLE NODE FROM GETTING CALLBACK".

Is there the same issue with
```
status = result.wait_for(std::chrono::seconds(0));
std::this_thread::sleep_for(std::chrono::seconds(1)));
```
?

**Comment by klaxalk** [comment]
Hey Gaël! I don't think it is an issue with std:: routines, but with the ROS2 multi-threaded executor. I assume that ROS2 does the whole outgoing service call asynchronously by putting it into some queue to be called later. Currently, the multithreaded executor in a Component seems to be broken. And since I call the service from a timer callback, the whole node hangs while waiting for the _future_ and the service never gets called.

**Comment by galou** [comment]
Thanks, Tomáš! I actually also had the issue when programming a GUI for ROS2 in Qt and ended up with using async calls. I would have taken less time to debug my code with sync calls, had I read what you wrote on Discourse.
